version: '3.9'

services:
  redis:
    image: redis
    restart: always
    container_name: 'demo_app_redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'demo_app_django'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
  celery:
    build: .
    command: celery -A core worker -l info -B
    container_name: 'my_demo_app_celery'
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
